datasets = {
    "uci_adult": {
        "path": "UCI_adult/adult.csv",
        "sep": ",",
        "drop_cols": ["fnlwgt", "education"],
        "data_types": [
            ("age", "positive int"),
            ("workclass", "categorical"),
            ("education-num", "positive int"),
            ("marital-status", "categorical"),
            ("occupation", "categorical"),
            ("relationship", "categorical"),
            ("race", "categorical"),
            ("sex", "categorical binary"),
            ("capital-gain", "positive float"),
            ("capital-loss", "positive float"),
            ("hours-per-week", "positive int"),
            ("native-country", "categorical"),
            ("salary", "categorical binary"),
        ],
    },
    "kaggle_cardio": {
        "path": "kaggle_cardio_disease/cardio_train.csv",
        "sep": ";",
        "drop_cols": ["id"],
        "data_types": [
            ("age", "positive int"),
            ("gender", "categorical"),
            ("height", "positive int"),
            ("weight", "positive int"),
            ("ap_hi", "positive int"),
            ("ap_lo", "positive int"),
            ("cholesterol", "categorical"),
            ("gluc", "categorical"),
            ("smoke", "categorical"),
            ("alco", "categorical"),
            ("active", "categorical"),
            ("cardio", "categorical"),
        ],
    },
    "node": {
        "path": "NodeMetricsUpdate_10.csv",
        "sep": ",",
        "drop_cols": ["timestamp", "nodeid"],
        "data_types": [
            ("cpu_utilization", "positive float"),
            ("memory_utilization", "positive float")
        ],
    },
    "1tb": {
        "path": "/home/azureuser/drive1/train_data/fake_logs_172.csv",
        "sep": ",",
        "drop_cols": [],
        "data_types": [
            ("continuous_0", "positive float"),
            ("continuous_1", "positive float"),
            ("continuous_2", "positive float"),
            ("continuous_3", "positive float"),
            ("continuous_4", "positive float"),
            ("continuous_5", "positive float"),
            ("continuous_6", "positive float"),
            ("continuous_7", "positive float"),
        ],
    },
    "cisco": {
        "path": "/home/azureuser/drive1/data/cisco_network_traffic.csv",
        "sep": ",",
        "drop_cols": ["time"],
        "data_types": [
            ("input-data-rate", "positive float"),
            ("input-load", "positive float"),
            ("input-packet-rate", "positive float"),
            ("load-interval", "categorical"),
            ("output-data-rate", "positive float"),
            ("output-load", "positive float"),
            ("output-packet-rate", "positive float"),
            ("reliability", "categorical"),
        ],
    },
    "cisco_preproc": {
        "path": "/home/azureuser/drive1/data/cisco_preproc.csv",
        "sep": ",",
        "drop_cols": [],
        "data_types": [
            ("load-interval.value0", "categorical binary"),
            ("load-interval.value1", "categorical binary"),
            ("reliability.value0", "categorical binary"),
            ("reliability.value1", "categorical binary"),
            ("reliability.value2", "categorical binary"),
            ("reliability.value3", "categorical binary"),
            ("input-packet-rate.component.value0", "categorical binary"),
            ("input-packet-rate.component.value1", "categorical binary"),
            ("input-packet-rate.component.value2", "categorical binary"),
            ("input-packet-rate.component.value3", "categorical binary"),
            ("input-packet-rate.component.value4", "categorical binary"),
            ("input-packet-rate.component.value5", "categorical binary"),
            ("input-packet-rate.component.value6", "categorical binary"),
            ("input-packet-rate.component.value7", "categorical binary"),
            ("input-packet-rate.component.value8", "categorical binary"),
            ("input-packet-rate.component.value9", "categorical binary"),
            ("input-load.component.value0", "categorical binary"),
            ("input-load.component.value1", "categorical binary"),
            ("input-load.component.value2", "categorical binary"),
            ("input-load.component.value3", "categorical binary"),
            ("input-load.component.value4", "categorical binary"),
            ("input-load.component.value5", "categorical binary"),
            ("input-load.component.value6", "categorical binary"),
            ("input-load.component.value7", "categorical binary"),
            ("input-load.component.value8", "categorical binary"),
            ("output-data-rate.component.value0", "categorical binary"),
            ("output-data-rate.component.value1", "categorical binary"),
            ("output-data-rate.component.value2", "categorical binary"),
            ("output-data-rate.component.value3", "categorical binary"),
            ("output-data-rate.component.value4", "categorical binary"),
            ("output-data-rate.component.value5", "categorical binary"),
            ("output-data-rate.component.value6", "categorical binary"),
            ("output-data-rate.component.value7", "categorical binary"),
            ("input-data-rate.component.value0", "categorical binary"),
            ("input-data-rate.component.value1", "categorical binary"),
            ("input-data-rate.component.value2", "categorical binary"),
            ("input-data-rate.component.value3", "categorical binary"),
            ("input-data-rate.component.value4", "categorical binary"),
            ("input-data-rate.component.value5", "categorical binary"),
            ("input-data-rate.component.value6", "categorical binary"),
            ("input-data-rate.component.value7", "categorical binary"),
            ("input-data-rate.component.value8", "categorical binary"),
            ("output-packet-rate.component.value0", "categorical binary"),
            ("output-packet-rate.component.value1", "categorical binary"),
            ("output-packet-rate.component.value2", "categorical binary"),
            ("output-packet-rate.component.value3", "categorical binary"),
            ("output-packet-rate.component.value4", "categorical binary"),
            ("output-packet-rate.component.value5", "categorical binary"),
            ("output-packet-rate.component.value6", "categorical binary"),
            ("output-packet-rate.component.value7", "categorical binary"),
            ("output-packet-rate.component.value8", "categorical binary"),
            ("output-load.component.value0", "categorical binary"),
            ("output-load.component.value1", "categorical binary"),
            ("output-load.component.value2", "categorical binary"),
            ("output-load.component.value3", "categorical binary"),
            ("output-load.component.value4", "categorical binary"),
            ("output-load.component.value5", "categorical binary"),
            ("output-load.component.value6", "categorical binary"),
            ("output-load.component.value7", "categorical binary"),
            ("output-load.component.value8", "categorical binary"),
            ("input-packet-rate.normalized", "positive float"),
            ("input-load.normalized", "positive float"),
            ("output-data-rate.normalized", "positive float"),
            ("input-data-rate.normalized", "positive float"),
            ("output-packet-rate.normalized", "positive float"),
            ("output-load.normalized", "positive float")
        ]
    },
    "appraise": {
        "path": "/home/azureuser/drive1/data/appraise_netflow_traffic_features.csv",
        "sep": ",",
        "drop_cols": [],
        "data_types": [
            ("IN_PKTS", "positive int"),
            ("IN_BYTES", "positive int"),
            ("OUT_PKTS", "positive int"),
            ("OUT_BYTES", "positive int")
        ],
    },
}
