datasets = {
    "uci_adult": {
        "path": "UCI_adult/adult.csv",
        "sep": ",",
        "drop_cols": ["fnlwgt", "education"],
        "data_types": [
            ("age", "positive int"),
            ("workclass", "categorical"),
            ("education-num", "positive int"),
            ("marital-status", "categorical"),
            ("occupation", "categorical"),
            ("relationship", "categorical"),
            ("race", "categorical"),
            ("sex", "categorical binary"),
            ("capital-gain", "positive float"),
            ("capital-loss", "positive float"),
            ("hours-per-week", "positive int"),
            ("native-country", "categorical"),
            ("salary", "categorical binary"),
        ],
    },
    "kaggle_cardio": {
        "path": "kaggle_cardio_disease/cardio_train.csv",
        "sep": ";",
        "drop_cols": ["id"],
        "data_types": [
            ("age", "positive int"),
            ("gender", "categorical"),
            ("height", "positive int"),
            ("weight", "positive int"),
            ("ap_hi", "positive int"),
            ("ap_lo", "positive int"),
            ("cholesterol", "categorical"),
            ("gluc", "categorical"),
            ("smoke", "categorical"),
            ("alco", "categorical"),
            ("active", "categorical"),
            ("cardio", "categorical"),
        ],
    },
    "node": {
        "path": "NodeMetricsUpdate_10.csv",
        "sep": ",",
        "drop_cols": ["timestamp", "nodeid"],
        "data_types": [
            ("cpu_utilization", "positive float"),
            ("memory_utilization", "positive float")
        ],
    },
    "1tb": {
        "path": "/home/azureuser/drive1/train_data/fake_logs_172.csv",
        "sep": ",",
        "drop_cols": [],
        "data_types": [
            ("continuous_0", "positive float"),
            ("continuous_1", "positive float"),
            ("continuous_2", "positive float"),
            ("continuous_3", "positive float"),
            ("continuous_4", "positive float"),
            ("continuous_5", "positive float"),
            ("continuous_6", "positive float"),
            ("continuous_7", "positive float"),
        ],
    },
    "cisco": {
        "path": "/home/azureuser/drive1/data/cisco_network_traffic.csv",
        "sep": ",",
        "drop_cols": ["time"],
        "data_types": [
            ("input-data-rate", "positive float"),
            ("input-load", "positive float"),
            ("input-packet-rate", "positive float"),
            ("load-interval", "categorical"),
            ("output-data-rate", "positive float"),
            ("output-load", "positive float"),
            ("output-packet-rate", "positive float"),
            ("reliability", "categorical"),
        ],
    },
    "cisco_preproc": {
        "path": "/home/azureuser/drive1/data/cisco_preproc.csv",
        "sep": ",",
        "drop_cols": [],
        "data_types": [
            ("load-interval.value0", "categorical binary"),
            ("load-interval.value1", "categorical binary"),
            ("reliability.value0", "categorical binary"),
            ("reliability.value1", "categorical binary"),
            ("reliability.value2", "categorical binary"),
            ("reliability.value3", "categorical binary"),
            ("input-packet-rate.component.value0", "categorical binary"),
            ("input-packet-rate.component.value1", "categorical binary"),
            ("input-packet-rate.component.value2", "categorical binary"),
            ("input-packet-rate.component.value3", "categorical binary"),
            ("input-packet-rate.component.value4", "categorical binary"),
            ("input-packet-rate.component.value5", "categorical binary"),
            ("input-packet-rate.component.value6", "categorical binary"),
            ("input-packet-rate.component.value7", "categorical binary"),
            ("input-packet-rate.component.value8", "categorical binary"),
            ("input-packet-rate.component.value9", "categorical binary"),
            ("input-load.component.value0", "categorical binary"),
            ("input-load.component.value1", "categorical binary"),
            ("input-load.component.value2", "categorical binary"),
            ("input-load.component.value3", "categorical binary"),
            ("input-load.component.value4", "categorical binary"),
            ("input-load.component.value5", "categorical binary"),
            ("input-load.component.value6", "categorical binary"),
            ("input-load.component.value7", "categorical binary"),
            ("input-load.component.value8", "categorical binary"),
            ("output-data-rate.component.value0", "categorical binary"),
            ("output-data-rate.component.value1", "categorical binary"),
            ("output-data-rate.component.value2", "categorical binary"),
            ("output-data-rate.component.value3", "categorical binary"),
            ("output-data-rate.component.value4", "categorical binary"),
            ("output-data-rate.component.value5", "categorical binary"),
            ("output-data-rate.component.value6", "categorical binary"),
            ("output-data-rate.component.value7", "categorical binary"),
            ("input-data-rate.component.value0", "categorical binary"),
            ("input-data-rate.component.value1", "categorical binary"),
            ("input-data-rate.component.value2", "categorical binary"),
            ("input-data-rate.component.value3", "categorical binary"),
            ("input-data-rate.component.value4", "categorical binary"),
            ("input-data-rate.component.value5", "categorical binary"),
            ("input-data-rate.component.value6", "categorical binary"),
            ("input-data-rate.component.value7", "categorical binary"),
            ("input-data-rate.component.value8", "categorical binary"),
            ("output-packet-rate.component.value0", "categorical binary"),
            ("output-packet-rate.component.value1", "categorical binary"),
            ("output-packet-rate.component.value2", "categorical binary"),
            ("output-packet-rate.component.value3", "categorical binary"),
            ("output-packet-rate.component.value4", "categorical binary"),
            ("output-packet-rate.component.value5", "categorical binary"),
            ("output-packet-rate.component.value6", "categorical binary"),
            ("output-packet-rate.component.value7", "categorical binary"),
            ("output-packet-rate.component.value8", "categorical binary"),
            ("output-load.component.value0", "categorical binary"),
            ("output-load.component.value1", "categorical binary"),
            ("output-load.component.value2", "categorical binary"),
            ("output-load.component.value3", "categorical binary"),
            ("output-load.component.value4", "categorical binary"),
            ("output-load.component.value5", "categorical binary"),
            ("output-load.component.value6", "categorical binary"),
            ("output-load.component.value7", "categorical binary"),
            ("output-load.component.value8", "categorical binary"),
            ("input-packet-rate.normalized", "positive float"),
            ("input-load.normalized", "positive float"),
            ("output-data-rate.normalized", "positive float"),
            ("input-data-rate.normalized", "positive float"),
            ("output-packet-rate.normalized", "positive float"),
            ("output-load.normalized", "positive float")
        ]
    },
    "appraise": {
        "path": "/home/ericwang/TableDiffusion2/data/appraise_preproc.parquet",
        "sep": ",",
        "drop_cols": ['IPV4_SRC_ADDR', 'IPV4_DST_ADDR'],
        "data_types": [
            ("IN_PKTS", "positive int"),
            ("IN_BYTES", "positive int"),
            ("OUT_PKTS", "positive int"),
            ("OUT_BYTES", "positive int"),
            ("TOTAL_FLOWS_EXP", "positive int"),
            ("ANOMALY", "categorical binary"),
            ('L4_SRC_PORT_0', 'float'),
            ('L4_SRC_PORT_1', 'float'),
            ('L4_SRC_PORT_2', 'float'),
            ('L4_SRC_PORT_3', 'float'),
            ('L4_SRC_PORT_4', 'float'),
            ('L4_SRC_PORT_5', 'float'),
            ('L4_SRC_PORT_6', 'float'),
            ('L4_SRC_PORT_7', 'float'),
            ('L4_SRC_PORT_8', 'float'),
            ('L4_SRC_PORT_9', 'float'),
            ('L4_DST_PORT_0', 'float'),
            ('L4_DST_PORT_1', 'float'),
            ('L4_DST_PORT_2', 'float'),
            ('L4_DST_PORT_3', 'float'),
            ('L4_DST_PORT_4', 'float'),
            ('L4_DST_PORT_5', 'float'),
            ('L4_DST_PORT_6', 'float'),
            ('L4_DST_PORT_7', 'float'),
            ('L4_DST_PORT_8', 'float'),
            ('L4_DST_PORT_9', 'float'),
            ('PROTOCOL_0', 'float'),
            ('PROTOCOL_1', 'float'),
            ('PROTOCOL_2', 'float'),
            ('PROTOCOL_3', 'float'),
            ('PROTOCOL_4', 'float'),
            ('PROTOCOL_5', 'float'),
            ('PROTOCOL_6', 'float'),
            ('PROTOCOL_7', 'float'),
            ('PROTOCOL_8', 'float'),
            ('PROTOCOL_9', 'float'),
        ],
    },
    "nfuq_v2": {
        "path": "/home/ericwang/vae_cloud_computing/data/raw/NF_UQ.csv",
        "sep": ",",
        "drop_cols": ["IPV4_SRC_ADDR", "IPV4_DST_ADDR"],
        "data_types": [
            ("IN_PKTS", "positive int"),
            ("IN_BYTES", "positive int"),
            ("OUT_PKTS", "positive int"),
            ("OUT_BYTES", "positive int"),
            ("L4_SRC_PORT", "positive int"),
            ("L4_DST_PORT", "positive int"),
            ("PROTOCOL", "positive int"),
            ("FLOW_DURATION_MILLISECONDS", "positive int"),
            ("Label", "categorical binary")
        ],
    },
}
